oscillo/urls.py
from django.urls import path
from oscillo import views

app_name = 'oscillo'
main = views.Main()


urlpatterns = [
    path('', main.oscilloSelect, name='oscilloSelect'),
    path('start/', main.index, name="start"),
    path("settings/", main.settings, name="settings"),
    path("data/", main.getData, name="data"),
    path("dataF/<int:filePosition>/<str:fileName>/", main.getFileData, name="dataF"),
    path("dataR/", main.getRawData, name="dataR"),
    path("oscilloSelect/", main.oscilloSelect, name="oscilloSelect"),
    path("setNewColors/<int:UID>/", views.SetNewColors, name="SetNewColors"),
    path("setThemePreference/<int:UID>/", views.setThemePreference, name="setThemePreference"),
    path("changePasswd/", views.changePasswd, name="changePasswd"),

    #User related patterns
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('disconnect/', views.disconnect, name='disconnect'),
    path('profile/', views.profile, name="profile"),
]

starecontrol_own/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oscillo/', include('oscillo.urls')),
]

oscillo/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user
    

class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(label="Username or Email")

    def __init__(self, *args, **kwargs):
        super(CustomAuthenticationForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control'})
        self.fields['password'].widget.attrs.update({'class': 'form-control'})


class UserUpdateForm(forms.Form):
    username = forms.CharField(
        max_length=100, 
        label="Username",
        widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'})
    )

    first_name = forms.CharField(
        max_length=100,
        label="First name",
        widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'})
    )

    last_name = forms.CharField(
        max_length=100,
        label="Last name",
        widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'})
    )

    email = forms.EmailField(
        max_length=100,
        label="Email",
        widget=forms.TextInput(attrs={'class': 'form-control', 'disabled': 'disabled'})
    )


class PasswordUpdateForm(forms.Form):
    currentPassword = forms.CharField(
        max_length=100,
        label="Current password",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    newPassword1 = forms.CharField(
        max_length=100,
        label="New password",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    
    newPassword2 = forms.CharField(
        max_length=100,
        label="Confirm new password",
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )


class OscilloSettingsForm(forms.Form):
    MODE_CHOICES = (
        ('REAL-TIME', 'Real-Time'),
        ('FILE', 'File'),
    )

    mode = forms.ChoiceField(
        choices=MODE_CHOICES,
        label='Mode :',
        initial='REAL-TIME',
        widget=forms.Select(attrs={'onchange': 'updateFormVisibility();', 'class': 'form-control', "size": "2"}),
    )

    channels = forms.IntegerField(
        label='Number of Channels : ',
        initial=4,
        min_value=1,
        max_value=10,
        widget=forms.NumberInput(attrs={'placeholder': '3', 'class': 'form-control'}),
        required=False
    )
    freq = forms.FloatField(
        label='Frequency (Hz) : ',
        initial=1e8,
        min_value=1.0,
        max_value=1e9,
        widget=forms.NumberInput(attrs={'placeholder': '1e8', 'class': 'form-control'}),
        required=False
    )
    nb = forms.IntegerField(
        label='Samples per frame : ',
        initial=1024,
        min_value=32,
        max_value=4096,
        widget=forms.NumberInput(attrs={'placeholder': 'Enter number of samples', 'class': 'form-control'}),
        required=False
    )
    voltage = forms.FloatField(
        label='Voltage (V) : ',
        initial=2.2,
        min_value=0.1,
        max_value=50,
        widget=forms.NumberInput(attrs={'placeholder': 'Enter voltage in volts', 'class': 'form-control'}),
        required=False
    )
    bits = forms.IntegerField(
        label='Bit Depth : ',
        initial=16,
        min_value=14,
        max_value=64,
        widget=forms.NumberInput(attrs={'placeholder': 'Enter bit depth', 'class': 'form-control'}),
        required=False
    )

    file = forms.FileField(
        label='Select a .osc file', 
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'}), 
        required=False
    )

oscillo/views.py
# Backend-related imports
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.views.generic import TemplateView
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from tempfile import NamedTemporaryFile

# Python general imports
import random
import json
import socket
import os
import struct
import numpy
from shutil import rmtree

# User-related imports
from django.contrib.auth.models import User
# from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import (
    CustomUserCreationForm, CustomAuthenticationForm, OscilloSettingsForm, UserUpdateForm, PasswordUpdateForm
)
from .models import FavoriteColors


def clear_temp_files(directory):
    """
    this function is here to clear out completely a directory given as a parameter.
    """
    if os.path.exists(directory):
        for filename in os.listdir(directory):
            file_path = os.path.join(directory, filename)
            try:
                if os.path.isfile(file_path) or os.path.islink(file_path):
                    os.unlink(file_path)
                elif os.path.isdir(file_path):
                    rmtree(file_path)
            except Exception as e:
                print(f'Failed to delete {file_path}. Reason: {e}')

def clear_console():
    if os.name == 'nt':
        os.system('cls')  #Windows (we never know..)
    else:
        os.system('clear') #Unix/Linux/MacOS

class Main(TemplateView):
    #This 'context' variable is what tells us what to expect before rendering the actual oscilloscope screen.
    #During testing these values need to be changed by hand here but later on will sent via the server depending on what the user selected
    context = {"mode": "NA", "channels": 3, "freq": 1e8, "nb": 1024, "voltage": 2.2, "bits": 16, "file_path": "NA", "file_position": 0, "theme": "dark", "gridOpacity": 0.5}

    sock: socket = None

    def index(self, request):
        data = {}
        for i in range(1, 11):#set to 1, 11 to generate 10 random channels
            channel = f"CH{i}"
            voltage = random.uniform(0, 8)
            data[channel] = {"voltage": voltage}
        
        colorSetsLight, colorSetsDark = get_user_favorite_colors(request)

        #assign colors to each channel
        c = 0
        for channel in data:
            data[channel]['colorLight'] = colorSetsLight[c]
            data[channel]['colorDark'] = colorSetsDark[c]

            c += 1

        if self.context['mode'] == 'FILE':
            file_size = request.session.get('file_size', 0)
            print(f"Getting ready to render the page with a file that has a size of {file_size:.2f} MB")

        return render(request, 'oscillo/graph.html', {"channels":data})
    

    def oscilloSelect(self, request):
        if request.method == 'POST':
            form = OscilloSettingsForm(request.POST, request.FILES)
            if form.is_valid():
                if form.cleaned_data['mode'] == 'FILE':
                    self.context['channels'] = 4
                    self.context['freq'] = 1e8
                    self.context['nb'] = 1024
                    self.context['voltage'] = 2.2 #normal values are -1.1V+1.1V so 2.2V total range.
                    self.context['bits'] = 16
                    self.context['mode'] = 'FILE'

                    #Handle the file upload.
                    print("Getting file size")
                    file = form.cleaned_data['file']
                    if file is None:
                        form = OscilloSettingsForm()
                        return render(request, 'oscillo/select.html', {'form': form, "error_message": "Please select a file to upload."})
                    file_size_in_bytes = file.size
                    file_size_in_mb = file_size_in_bytes / (1024 * 1024)
                    print(f"Uploaded file size: {file_size_in_mb:.2f} MB")
                    print(f"File name : {file.name}")
                    strExt = file.name.split(".")[-1]
                    if strExt not in ["osc", "dat"]:
                        form = OscilloSettingsForm()
                        return render(request, 'oscillo/select.html', {'form': form, "error_message": "The file given was not a .osc file."})

                    temp_files_directory = os.path.join(settings.BASE_DIR, 'temp_files')
                    clear_temp_files(temp_files_directory)

                    temp_file = NamedTemporaryFile(delete=False, suffix="."+strExt, dir=temp_files_directory)
                    for chunk in file.chunks():
                        temp_file.write(chunk)
                    temp_file.close()

                    print(f"File saved to temporary location: {temp_file.name}")

                    request.session['file_path'] = temp_file.name
                    request.session['file_size'] = file_size_in_mb
                    self.context['file_path'] = temp_file.name
                    print("FIle infos saved to session")

                else:
                    self.context['channels'] = form.cleaned_data['channels']
                    self.context['freq'] = form.cleaned_data['freq']
                    self.context['nb'] = form.cleaned_data['nb']
                    self.context['voltage'] = form.cleaned_data['voltage']
                    self.context['bits'] = form.cleaned_data['bits']
                    self.context['mode'] = form.cleaned_data['mode']
                return redirect('/oscillo/start/')
        else:
            form = OscilloSettingsForm()
            return render(request, 'oscillo/select.html', {'form': form})


    def settings(self, request):
        try:
            user = User.objects.get(pk=request.user.id)
            favorite_colors, created = FavoriteColors.objects.get_or_create(user=user)
            theme = favorite_colors.Theme_saved
            gridOpacity = favorite_colors.Grid_opacity
            self.context['theme'] = theme
            self.context['gridOpacity'] = gridOpacity
        except:
            print("No user logged.")
        
        return HttpResponse(json.dumps(self.context))


    def getData(self, request):
        if not self.sock:
            self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sock.bind(("127.0.0.1", 7888))
            self.sock.settimeout(1)
            print("bound")

        try:
            #Here we update the amount of bytes we expect to receive based off of the settings we received.
            #Nb of channels * 1024 samples per frame * 2 bytes per sample
            expected_data_to_send = self.context['channels'] * 1024 * 2

            data, _ = self.sock.recvfrom(expected_data_to_send)
            print(f"Data received is {len(data)} bytes long")
            return HttpResponse(data, content_type="application/octet-stream")
        except socket.timeout:
            return HttpResponse("No data received so far..", status=408)

    def getRawData(self, request):
        if not self.sock:
            self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            self.sock.bind(("127.0.0.1", 7777))
            self.sock.settimeout(1)
            print("bound")

        data, adr = self.sock.recvfrom(8192)
        print("received", len(data))
        return HttpResponse(data)

    def getFileData(self, request, filePosition, fileName):
        # clear_console()
        print(f"GET DATA AT POSITION {filePosition} FOR FILE {fileName}")

        completeFilePath = os.path.join(settings.BASE_DIR, 'temp_files') + "/" + fileName
        Data = read_file(completeFilePath, filePosition)
        # print("return", Data)
        if Data == "EOF":  # End Of File
            Data = read_file(completeFilePath, 0)

        print("====================================================")
        print("           Data returned from the file")
        print("             --------------------")
        print("Number of samples: ", Data[0][0])
        print("New position in the file: ", Data[1])
        print("Length of CH1 : ", len(Data[0][2]))
        print("Length of CH2 : ", len(Data[0][3]))
        print("Length of CH3 : ", len(Data[0][4]))
        print("Length of CH4 : ", len(Data[0][5]))
        print("Header Data : ", Data[0][1])
        print("====================================================")
        return JsonResponse(Data, safe=False)


def SetNewColors(request, UID):
    if request.method == 'POST':
        try:
            if UID == 0:#User not registered
                return JsonResponse({"status": "error", "message": "You need to be registered in order to save your color preferences."}, status=315)

            data = json.loads(request.body)
            ColorChoicesDark = data.get('ColorChoicesDark', [])
            ColorChoicesLight = data.get('ColorChoicesLight', [])
            gridOpacity = data.get('gridOpacity', [])

            print(f"User ID: {UID}")
            print(f"ColorChoicesDark: {ColorChoicesDark}")
            print(f"ColorChoicesLight: {ColorChoicesLight}")

            user = User.objects.get(pk=UID)

            favorite_colors, created = FavoriteColors.objects.get_or_create(user=user)

            favorite_colors.CH1_L = ColorChoicesLight[0]
            favorite_colors.CH2_L = ColorChoicesLight[1]
            favorite_colors.CH3_L = ColorChoicesLight[2]
            favorite_colors.CH4_L = ColorChoicesLight[3]
            favorite_colors.CH5_L = ColorChoicesLight[4]
            favorite_colors.CH6_L = ColorChoicesLight[5]
            favorite_colors.CH7_L = ColorChoicesLight[6]
            favorite_colors.CH8_L = ColorChoicesLight[7]
            favorite_colors.CH9_L = ColorChoicesLight[8]
            favorite_colors.CH10_L = ColorChoicesLight[9]

            favorite_colors.CH1_D = ColorChoicesDark[0]

oscillo/templates/oscillo/graph.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OSCILLOSCOPE</title>
    {% load static %}
    <link rel="icon" type="image/png" href={% static "IMAGES/oscillo-icon.png" %}>
    <link rel="stylesheet" type="text/css" href={% static 'FILES/css/styles.css' %}>
    <script src={% static "FILES/js/input-knob.js" %}></script>
    <script src={% static "FILES/js/fft.js" %}></script>
</head>
<body>
    <div id="toast"><!--message goes here--></div>
    {% csrf_token %}<!--Token used during http request and such by the javascript-->
    <script>
        let DocFileName = "module-MAIN-PAGE.html";

        const channelsMetaData = {{ channels|safe }};
        {% if user.is_authenticated %}
            const userId = {{ user.id }};
        {% else %}
            const userId = 0;//0 can't normally be assigned to a UID.
        {% endif %}
    </script>
    <section>
        <div id="top-line"><!--Contains the top line of the screen-->

        </div>
        <div id="middle-line">
            <div id="scroll-bar" class="canvas-scrollbars-dark">
                <div id="scroller-CH1" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH2" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH3" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH4" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH5" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH6" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH7" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH8" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH9" class="scrollers" style="display: none;"></div>
                <div id="scroller-CH10" class="scrollers" style="display: none;"></div>
            </div>
            <div id="sub-div-horizontal-offset">
                <div id="scrollbar-horizontal" class="canvas-scrollbars-dark">
                    <div id="vertical-scroller-A" class="vertical-scrollers" style="display: none;"></div>
                    <div id="scroller-Horizontal"></div>
                    <div id="vertical-scroller-B" class="vertical-scrollers" style="display: none;"></div>
                </div>
                <canvas id="oscilloscope_screen" class="canvas-dark" width="1200" height="800">

                </canvas>
                <div id="info-display-oscilloscope" class="canvas-scrollbars-dark">
                    <span id="vpdiv-mesurements">
                        <p id="mes-CH1" class="chanmeasures"></p>
                        <p id="mes-CH2" class="chanmeasures"></p>
                        <p id="mes-CH3" class="chanmeasures"></p>
                        <p id="mes-CH4" class="chanmeasures"></p>
                        <p id="mes-CH5" class="chanmeasures"></p>
                        <p id="mes-CH6" class="chanmeasures"></p>
                        <p id="mes-CH7" class="chanmeasures"></p>
                        <p id="mes-CH8" class="chanmeasures"></p>
                        <p id="mes-CH9" class="chanmeasures"> </p>
                        <p id="mes-CH10" class="chanmeasures"></p>
                    </span>
                    <span id="mathres-measurements">
                        <p id="mathres-1">--.--</p>
                    </span>
                    <span id="tpdiv-measurement">
                        <p id="tpdiv-value">-- xx/div</p>
                    </span>
                </div>
                <span id="auto-measures-display" class="canvas-scrollbars-dark">
                    <p id="vpp-measure" class="auto-measure"></p>
                    <p id="min-measure" class="auto-measure"></p>
                    <p id="max-measure" class="auto-measure"></p>
                    <p id="avg-measure" class="auto-measure"></p>
                    <p id="mid-measure" class="auto-measure"></p>
                    <p id="rms-measure" class="auto-measure"></p>
                    <p id="avg-freq-measure" class="auto-measure"></p>
                    <p id="max-freq-measure" class="auto-measure"></p>
                    <p id="min-freq-measure" class="auto-measure"></p>
                </span>
            </div>
            <div id="scroll-bar-horizontal-cursors" class="canvas-scrollbars-dark">
                <div id="scroller-horizontal-A" style="display: none;">

                </div>
                <div id="trigger-cursor" style="display: none;">
                    T
                </div>
                <div id="scroller-horizontal-B" style="display: none;">

                </div>
            </div>
        </div>
        <div id="bottom-line"><!--Contains the bottom line of the screen-->
        </div>
    </section>
    <aside id="aside"><!--Contains all the buttons to interact with the oscilloscope-->
        <nav id="user-related-actions">
            {% if request.user.is_authenticated %}
                <a href={% url "oscillo:disconnect" %}><button>Logout</button></a>
                <a href={% url "oscillo:profile" %}><button>Profile</button></a>
            {% else %}
                <a href={% url "oscillo:login" %}><button>Login</button></a>
                <a href={% url "oscillo:register" %}><button>Register</button></a>
            {% endif %}
            <a href={% url "oscillo:oscilloSelect" %}><button>Settings</button></a>
        </nav>
        <div id="channel-select-div" class="main-divs-aside"><!--Contains the Channel selections-->
            <span>
                <button id="CH1" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH1</p></button>
                <button id="CH2" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH2</p></button>
                <button id="CH3" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH3</p></button>
                <button id="CH4" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH4</p></button>
                <button id="CH5" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH5</p></button>
            </span>

            <span>
                <button id="CH6" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH6</p></button>
                <button id="CH7" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH7</p></button>
                <button id="CH8" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH8</p></button>
                <button id="CH9" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH9</p></button>
                <button id="CH10" class="channel-not-displayed ch-button" role="button"><p style="margin: 0px;">CH10</p></button>
            </span>
            </span>
        </div>
        <div id="main-functions-div" class="main-divs-aside"><!--Contains the buttons to interact with the oscilloscope-->
            <span>
                <button id="run-stop" class="function-buttons">RUN</button>
                <button id="cursors" class="function-buttons">CURSORS</button>
                <button id="display" class="function-buttons">DISPLAY</button>
                <button id="trigger" class="function-buttons">TRIGGER</button>
                <button id="save" class="function-buttons">SAVE</button>
            </span>

            <span>
                <button id="autoset" class="function-buttons">AUTOSET</button>
                <button id="measure" class="function-buttons">MEASURE</button>
                <button id="print" class="function-buttons">PRINT</button>
                <button id="setup" class="function-buttons">SETUP</button>
                <button id="size" class="function-buttons">SIZE</button>
            </span>
        </div>
        <div id="knobs-div" class="main-divs-aside"><!--Contains the knobs to interact with the signal rendering-->
            <span>
                <!--Knob to change the vertical scaling of the signal (how many pixels per volt unit)-->
                <input 
                    type="range" 
                    class="input-knob" 
                    id="vertical-scaling"
                    data-src={% static "IMAGES/knob.png" %} 
                    data-sprites="100"
                    data-diameter="100"
                    style="
                        background-image: url({% static "IMAGES/knob.png" %} ); 
                        background-size: 100% 10100%; 
                        background-position: 0px -6400px;"
                    min="0"
                    max="10"
                    value="1"
                    step="0.01">
                <p>V/DIV</p>
            </span>

            <span>
                <!--Knob to change the horizontal scaling of the signal (how many micro-seconds per pixels)-->
                <input 
                    type="range" 
                    class="input-knob" 
                    id="horizontal-scaling"
                    data-src={% static "IMAGES/knob.png" %} 
                    data-sprites="100"
                    data-diameter="100"
                    style="
                        background-image: url({% static "IMAGES/knob.png" %} ); 
                        background-size: 100% 10100%; 
                        background-position: 0px -6400px;"
                    min="1"
                    step="1"
                    max="300"
                    value="50">
                <p>S/DIV</p>
            </span>
        </div>
    </aside>

    <!--Modal popup element (filled using javascript)-->
    <div id="modal" class="modal">
        <!-- Modal content -->
        <div class="modal-content">
          <span class="close">&times;</span>
          <div id="modal-generated-content">
            
          </div>
        </div>
      </div>

    <script src={% static 'FILES/js/drawings.js' %}></script>
    <script src={% static 'FILES/js/modal.js' %}></script>
    <script src={% static 'FILES/js/ui.js' %}></script>
    <script src={% static 'FILES/js/infoComputing.js' %}></script>
    <script src={% static 'FILES/js/infoExport.js' %}></script>
    <script src={% static 'FILES/js/triggerAndAutoset.js' %}></script>
    <script src={% static 'FILES/js/misc.js' %}></script>
    <script src={% static 'FILES/js/main.js' %}></script>

    <script>
    //====================== INTERACTIVE DOC LISTENER =======================
    document.addEventListener('keydown', function(event) {
        const modeSelectionInput = document.getElementById("id_mode");

        if (event.key === 'F1' || event.code === 'F1') {
            console.log("F1 pressed");
            event.preventDefault();
            let relativeStaticURI = "{% static 'DOCS/' %}";

            let fullUrl = window.location.origin + relativeStaticURI + DocFileName;
            let docWindow = window.open(fullUrl, '_blank');

            if (!docWindow || docWindow.closed || typeof docWindow.closed === 'undefined') {
                alert('You need to allow popups to open the documentation by pressing F1.');
            }
        }
    });
    </script>
</body>
</html>